services:  
  db:
    ports: 
      - "5432:5432"
    image: postgres:13
    environment:
      - POSTGRES_USER=flatRent
      - POSTGRES_PASSWORD=fernan
      - POSTGRES_DB=mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

# Volumen para persistir los datos de PostgreSQL
volumes:
  pgdata:
